# k8s/monitoring/prometheus-values.yaml
grafana:
  adminPassword: "banking123"
  sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard
      labelValue: "1"
      searchNamespace: ALL
  persistence:
    enabled: false

prometheus:
  prometheusSpec:
    retention: 7d
    storageSpec: {}
    serviceMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelector: {}
    serviceMonitorNamespaceSelector: {}

alertmanager:
  enabled: true

prometheus-node-exporter:
  enabled: true

kube-state-metrics:
  enabled: true
