sonar.projectKey=banking-event-sourcing
sonar.projectName=Banking Event Sourcing
sonar.projectVersion=1.0
sonar.sources=src
sonar.tests=tests
sonar.exclusions=node_modules/**,dist/**,coverage/**,k8s/**,docs/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
