sonar.projectKey=banking-event-sourcing
sonar.projectName=Banking Event Sourcing
sonar.projectVersion=1.0
sonar.sources=apps/monolith/src
sonar.tests=apps/monolith/tests
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,k8s/**,docs/**
sonar.javascript.lcov.reportPaths=apps/monolith/coverage/lcov.info
