apiVersion: v1
data:
  DATABASE_URL: cG9zdGdyZXM6Ly9wb3N0Z3Jlczpwb3N0Z3Jlc0Bwb3N0Z3Jlcy5iYW5raW5nLnN2Yy5jbHVzdGVyLmxvY2FsOjU0MzIvYmFua2luZw==
  READ_DATABASE_URL: cG9zdGdyZXM6Ly9wb3N0Z3Jlczpwb3N0Z3Jlc0Bwb3N0Z3Jlcy1yZWFkLmJhbmtpbmcuc3ZjLmNsdXN0ZXIubG9jYWw6NTQzMi9iYW5raW5nX3JlYWQ=
kind: Secret
metadata:
  name: banking-app-secrets
  namespace: banking
