apiVersion: v1
kind: Service
metadata:
  name: banking-app
  namespace: banking
spec:
  type: LoadBalancer
  selector:
    app: banking-app
  ports:
    - name: http
      port: 80
      targetPort: 3001
