apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - configmap.yaml
  - hpa.yaml
  - pdb.yaml
images:
  - name: banking-event-sourcing:app
    newName: ghcr.io/devicaro16/banking-event-sourcing
    newTag: latest
