apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: banking-dev
resources:
  - ../../base
patches:
  - path: configmap-patch.yaml
  - patch: |-
      - op: replace
        path: /spec/minReplicas
        value: 1
      - op: replace
        path: /spec/maxReplicas
        value: 2
    target:
      kind: HorizontalPodAutoscaler
images:
  - name: banking-event-sourcing:app
    newName: ghcr.io/devicaro16/banking-event-sourcing
    newTag: 85e8455
